import Accueil from "../components/Accueil";
import About from "../components/About";
import Layout from "../components/MyLayout";
import Projets from "../components/Projets";
import Skills from "../components/Skills";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Rova</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
				<Accueil />
				<About />
				<Skills />
				<Projets />
			</Layout>
		</>
	);
}
