import Accueil from "../components/Accueil";
import About from "../components/About";
import Layout from "../components/MyLayout";
import Projets from "../components/Projets";
import Skills from "../components/Skills";
import Head from "next/head";
import Script from "next/script";

export default function Home() {
	return (
		<>
			<Head>
				<title>Rova</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<script
					async
					src="https://www.googletagmanager.com/gtag/js?id=G-CJJ8ZGW2JD"
				></script>
				<script
					dangerouslySetInnerHTML={{
						__html: `
						window.dataLayer = window.dataLayer || [];
						function gtag(){dataLayer.push(arguments);}
						gtag('js', new Date());

						gtag('config', 'G-CJJ8ZGW2JD');
						`,
					}}
				/>
			</Head>

			<Layout>
				<Accueil />
				<About />
				<Skills />
				<Projets />
			</Layout>
		</>
	);
}
